services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    restart: always
    volumes:
      - ollama_data:/usr/share/ollama/
    deploy:
      resources:
        limits:
          memory: 30G
        reservations:
          memory: 24G
      
volumes:
  ollama_data:
    driver: local
    driver_opts:
      type: none
      device: /home/maintainer/Documents/ChatBotProjectEvaluation/implementation/Docker/ollama_data
      o: bind
